name: fetchAnnouncement.yml

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 3 1 * *"

jobs:
  FetchAnnouncement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Fetch calendar data
        run: pnpm tsx fetchCalendar.ts
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
