name: fetchTeachers

on:
  push:
    branches:
      - main

jobs:
  fetchLocations:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        term: [
          "95#1",
          "96#1",
          "96#2",
          "97#1",
          "97#2",
          "98#1",
          "98#2",
          "98#3",
          "98#5",
          "98#6",
          "99#1",
          "99#2",
          "99#3",
          "99#5",
          "99#6",
          "99#7",
          "100#1",
          "100#2",
          "100#3",
          "100#5",
          "100#6",
          "100#7",
          "101#1",
          "101#2",
          "101#5",
          "101#6",
          "101#7",
          "102#1",
          "102#2",
          "102#3",
          "102#5",
          "102#6",
          "102#7",
          "103#1",
          "103#2",
          "103#3",
          "103#5",
          "103#6",
          "103#7",
          "104#1",
          "104#2",
          "104#3",
          "104#5",
          "104#6",
          "104#7",
          "105#1",
          "105#2",
          "105#3",
          "105#5",
          "105#6",
          "105#7",
          "106#1",
          "106#2",
          "106#3",
          "106#5",
          "106#6",
          "106#7",
          "107#1",
          "107#2",
          "107#3",
          "108#1",
          "108#2",
          "108#3",
          "108#6",
          "109#1",
          "109#2",
          "109#3",
          "109#5",
          "109#6",
          "110#1",
          "110#2",
          "110#3",
          "110#5",
          "110#6",
          "110#7",
          "111#1",
          "111#2",
          "111#3",
          "111#5",
          "111#6",
          "111#7",
          "112#1",
          "112#2",
          "112#3",
          "112#5",
          "112#6",
          "112#7",
          "113#1",
          "113#2",
          "113#3",
          "113#5",
          "113#6",
          "113#7",
          "114#1",
          "114#3",
          "114#5",
          "114#6",
        ]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Fetch Teacher Classes
        run: pnpm tsx fetchTeacherClasses.ts ${{ matrix.term }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
