name: fetchLocations

on:
  push:
    branches:
      - main

  schedule:
    # Run only on 3, 6, 9, 12 months and the 3rd day of the month
    - cron: "0 0 3 3,6,9,12 *"

jobs:
  fetchLocations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Fetch Yms and Locations
        run: pnpm tsx fetchLocations.ts
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
