name: fetchTeachers

on:
  push:
    branches:
      - main

jobs:
  fetchLocations:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        term: [
          "105#1",
          "105#2",
          "105#3",
          "105#5",
          "105#6",
          "105#7",
          "106#1",
          "106#2",
          "106#3",
          "106#5",
          "106#6",
          "106#7",
          "107#1",
          "107#2",
          "107#3",
          "108#1",
          "108#2",
          "108#3",
          "108#6",
          "109#1",
          "109#2",
          "109#3",
          "109#5",
          "109#6",
        ]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Fetch Teacher Classes
        run: pnpm tsx fetchTeacherClasses.ts ${{ matrix.term }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.term }}
          path: ./dist

  deploy:
    needs: fetchLocations
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: ./dist
          merge-multiple: true
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
